image: gitlab-registry.cern.ch/linuxsupport/alma9-base

include:
  - project: 'ci-tools/container-image-ci-templates'
    file: 'helm.gitlab-ci.yml'
    ref: master

stages:
  - lint
  - validate
  - test
  - deploy

docs_lint:
  stage: lint
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - dnf install -y python-pip
    - python3 -m pip install linkcheckmd
    - python3 -m linkcheckmd -v README.md

yaml_lint:
  stage: lint
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - dnf install -y epel-release
    - dnf install -y yamllint
    - yamllint .

helm_lint:
  stage: lint
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  image: alpine/helm
  script:
    - helm lint --strict .

helm_docs_needs_running:
  stage: validate
  image: registry.cern.ch/docker.io/jnorwood/helm-docs:v1.14.2
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - helm-docs -o test.md
    - diff -ura test.md README.md

unittest:
  stage: test
  image: registry.cern.ch/docker.io/helmunittest/helm-unittest:3.17.0-0.7.2
  script:
    - helm unittest -f 'tests/**/*.yaml' .

helm_deploy:
  stage: deploy
  image: registry.cern.ch/kubernetes/ops:0.6.0
  rules:
    - if: '$CI_COMMIT_TAG'
  script: |
    helm package .
    echo ${CI_REGISTRY_PASSWORD} | helm registry login registry.cern.ch -u $CI_REGISTRY_USER --password-stdin
    helm push ${CHART_NAME}-$CI_COMMIT_TAG.tgz oci://${REGISTRY_CHART_PATH}
    echo -n "${HARBOR_SIGNKEY}" | base64 -d > .sign.key
    cosign login registry.cern.ch -u ${HARBOR_USER} -p ${HARBOR_TOKEN}
    cosign sign --key .sign.key -y "${REGISTRY_CHART_PATH}/${CHART_NAME}:${CI_COMMIT_TAG}"
  variables:
    CHART_NAME: landb-alias-controller
    COSIGN_PRIVATE_KEY: "$HARBOR_SIGNKEY"
    REGISTRY_CHART_PATH: registry.cern.ch/kubernetes/charts
