#!/usr/bin/env bash

# LanDB Alias Controller Helm Chart CHANGELOG generator
# SPDX-License-Identifier: Apache-2.0
#
# This script generates CHANGELOG.md by walking through the git history,
# grouping commits by version tags (if present) or by date.
#
# Follows a "Conventional Changelog"-inspired format.
#
# Usage:
#   .tools/update-changelog.sh
#
# Notes:
# - Requires git.
# - Ignores dependabot commits.
# - Respects .mailmap for contributor normalization.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

OUT="CHANGELOG.md"

{
    cat <<'EOH'
# LanDB Alias Controller Helm Chart Changelog

This file is autogenerated using [update-changelog.sh](.tools/update-changelog.sh).

All notable changes to the LanDB Alias Controller Helm Chart are listed here by release or date.
EOH
    echo

    # Check if the repo has any tags
    if git tag | grep -q .; then
        echo "## Versions"
        echo

        # List tags top-down (latest first)
        for tag in $(git tag --sort=-creatordate); do
            echo "### $tag"
            echo

            # Show commits for this tag (range: previous_tag..tag)
            prev_tag=$(git tag --sort=creatordate | awk "/^$tag\$/ {print x} {x=\$0}")

            if [[ -n "$prev_tag" ]]; then
                range="$prev_tag..$tag"
            else
                range="$tag"
            fi

            git log $range --pretty=format:'- (%h) %s — %aN' | \
                grep -v "dependabot" | \
                grep -v "Merge pull request" || true

            echo
        done
    else
        echo "## Unreleased (No tags detected)"
        echo

        # Group commits by date if no tags exist
        git log --date=short --pretty=format:'%ad %h %s — %aN' | \
            grep -v "dependabot" | \
            awk '
                {
                    date=$1;
                    sub($1 FS, "");
                    if (date != last_date) {
                        if (last_date != "") print "";
                        print "### " date;
                        print "";
                        last_date = date;
                    }
                    print "- (" $1 ") " substr($0, index($0,$2))
                }
            '
        echo
    fi

} > "$OUT"

echo "CHANGELOG.md updated."
