{{- if and .Values.cloudConfig.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "landb-alias-controller.fullname" . }}-cloud-config-reader
  namespace: {{ .Values.cloudConfig.namespace }}
  labels:
    {{- include "landb-alias-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.cloudConfig.name | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "landb-alias-controller.fullname" . }}-cloud-config-reader
  namespace: {{ .Values.cloudConfig.namespace }}
  labels:
    {{- include "landb-alias-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "landb-alias-controller.fullname" . }}-cloud-config-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "landb-alias-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
