apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "landb-alias-controller.fullname" . }}
  labels:
    {{- include "landb-alias-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "landb-alias-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "landb-alias-controller.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "landb-alias-controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "landb-alias-controller.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.args .Values.cloudConfig.enabled }}
          args:
            {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.cloudConfig.enabled }}
            - "--cloud-config-secret={{ .Values.cloudConfig.namespace }}/{{ .Values.cloudConfig.name }}"
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or .Values.secretEnv .Values.envFromSecret }}
          envFrom:
            {{- if .Values.secretEnv }}
            - secretRef:
                name: {{ include "landb-alias-controller.fullname" . }}-env
            {{- end }}
            {{- if .Values.envFromSecret }}
            - secretRef:
                name: {{ .Values.envFromSecret }}
            {{- end }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
