{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landb-alias-controller.fullname" . }}-env
  labels:
    {{- include "landb-alias-controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
